name: .NET Core

on:
  push:
    branches:
      - master
      - 'spike/**'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: [
          { framework: 'netcoreapp3.1', version: '3.1.x' }
          { framework: 'net5.0', version: '5.0.x' }
          { framework: 'net6.0', version: '6.0.x' }
        ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Setup .NET Core ${{ matrix.dotnet.version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet.version }}
    - name: Test
      run: dotnet test --framework ${{ matrix.dotnet.version }} /p:CollectCoverage=true /p:CoverletOutputFormat=lcov  /p:ExcludeByFile="**/PlatformAbstractions.cs" --no-restore --verbosity normal

    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: run-dotnet-${{ matrix.dotnet-version }}
        parallel: true

  coverage:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
